#!/bin/bash

#########################################################################
##  frankl (C) 2015
##  
##  USAGE:
##    improvefile <orig> <new>
##  This script generates a (bit-identical) copy of a file <orig> to
##  the file <new>.
##  
#########################################################################

if test -e "$2" ; then
  echo "the file $2 already exists, please delete it first"
  exit
fi


##  This utility is mainly meant for music files (and maybe certain filter and
##  program files for music playback).

## Hint: you may also use the new program 'cleancp' instead of this script

bufhrt --file="$1" --outfile="$2" --buffer-size=536870912 \
       --loops-per-second=2000 --bytes-per-second=8192000 \
       --dsyncs-per-second=100 --interval 


# older variant with --dsync 
##  For testing you may add the '--verbose' option. If there are more 
##  than a few dozen "bufhrt: delayed block xxxx" messages on an album
##  then reduce the value of the '--loops-per-second' parameter.
##  
##  You may also experiment with the '--bytes-per-second' value. Larger values
##  make the process faster. Lower values may lead to even better audible
##  results. But this needs to be tested in the individual setups.
##  
##  If you have enough RAM you may enlarge the value of the
##  '--buffer-size' argument to something larger than the size
##  of the biggest files you want to improve.

#bufhrt --file="$1" --dsync --outfile="$2" --buffer-size=50000000 \
#       --loops-per-second=100 --bytes-per-second=3276800 --interval 

# setting in version 0.8, often probably too many loops
#bufhrt --file="$1" --dsync --outfile="$2" --buffer-size=50000000 \
#       --loops-per-second=2000 --bytes-per-second=6144000 --interval 

